concourse/tasks/terraform_apply_cloudfoundry.yml
concourse/tasks/terraform_plan_cloudfoundry.yml
spec/tasks/terraform_apply_cloudfoundry/task_spec.rb
spec/tasks/terraform_plan_cloudfoundry/task_spec.rb

This required to invoke terraform init (as a replacement for terraform get: init also handles fetching modules).
"The downloaded plugins are installed to a subdirectory of the working directory, and are thus local to that working directory" according to https://www.terraform.io/docs/commands/init.html#plugin-installation
The pipeline only commits the tfstate file to git, so it should ignore this directort.
Updated spec files to expect the .terraform/ directory holding plugins and modules and added a SKIP_REMOTE_FLY_DOWNLOAD constant to ease tests debugging
Fix #23

Upgrading terraform to 0.10.2 and cloudfoundry provider to 0.9.1

---

concourse/pipelines/template/depls-pipeline.yml.erb
concourse/tasks/copy_deployment_required_files.yml
scripts/manifest/copy-deployment-required-files.sh
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/tasks/copy_deployment_required_files/additional-resource/a-depls.yml
spec/tasks/copy_deployment_required_files/task_spec.rb
spec/tasks/copy_deployment_required_files/template-resource/default-manifest-depls/default-manifest-depls.yml

The bosh deploy task still expects a manifest name, but it can be
provided by a xxx-tpl.yml or directly as xxx.yml
close #25

pipeline(depls): support deployment manifest without template

---

concourse/pipelines/template/depls-pipeline.yml.erb
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml

Switching to UAA authentication requires valid certificates. But theses
certificates weren't used by bosh-cli-v1.
We also use governmentpaas/bosh-cli-v2 instead of orangecloudfoundry
version tu use the latest bosh-cli-v2 (2.0.40)

pipeline(depls): upgrade to bosh-cli-v2 for [cloud|runtime]-config

---

concourse/pipelines/template/depls-pipeline.yml.erb
concourse/tasks/bosh_update_cloud_config.yml
concourse/tasks/bosh_update_runtime_config.yml
concourse/tasks/execute_deploy_script.yml
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/scripts/generate-depls/generate_depls_spec.rb
spec/tasks/bosh_update_cloud_config/task_spec.rb

This move reduces duplication across pipeline and easy test update.
We also add minimal integration test to ensure bosh login is executed.
We add pre requisite test to enforce the docker image used.

pipeline(depls): extract cloud and runtime task to dedicated files

---

concourse/pipelines/template/s3-br-upload-pipeline.yml.erb
concourse/pipelines/template/s3-stemcell-upload-pipeline.yml.erb
lib/ci_deployment_overview.rb
scripts/concourse-manual-pipelines-update.rb
scripts/generate-depls.rb
spec/scripts/generate-depls/fixtures/references/empty-s3-br-upload.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-stemcell-upload.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-br-upload-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-stemcell-upload-ref.yml
spec/scripts/generate-depls/generate_depls_for_s3_br_upload_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_s3_stemcell_upload_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_spec.rb
spec/scripts/generate-depls/test_helper.rb

This is a first step to be independent from bosh.io availability,
and to save bandwith.
Restrictions: 
- pipelines must be enabled for each root deployment
- only the current version and the latest version are uploaded (Concourse
is not able to load the full history)

pipeline(s3-*-upload): add pipeline to upload bosh releases or stemcells to s3

---

Readme.md
concourse/pipelines/template/tf-pipeline.yml.erb

for use by [cf-ops-automation-broker](https://github.com/orange-cloudfoundry/cf-ops-automation-broker) for on-demand terraform spec file execution.
Unlike existing pipelines, this one does not require human validation, so used be used with care.
TODO:

tf only pipeline

---

concourse/pipelines/template/tf-pipeline.yml.erb

Fix improper input mapping build triggers on secrets-<%=depls %>-trigger but was using secrets-full in the pipeline for TF apply.

Fix Tf pipeline

---

concourse/pipelines/template/depls-pipeline.yml.erb
lib/directory_initializer.rb
lib/secrets.rb
scripts/concourse-manual-pipelines-update.rb
spec/lib/directory_initializer_spec.rb
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/scripts/generate-depls/fixtures/templates/apps-depls/apps-depls-versions.yml
spec/scripts/generate-depls/fixtures/templates/delete-depls/delete-depls-versions.yml
spec/scripts/generate-depls/fixtures/templates/no-dependency-depls/no-dependency-depls-versions.yml
spec/scripts/generate-depls/fixtures/templates/simple-depls/simple-depls-versions.yml

pipeline(depls): move stemcell support from bosh.io to S3
Check-resource is also impacted as S3 resource requires a full scan path.
To avoid conflict with previous 'stemcell-name' properties, we use a new
property 'stemcell-main-name'. To get the full stemcell name, a concatenation of stemcell-name-prefix and stemcell-main-name is required.
Requires new concourse properties
stemcell-name-prefix
stemcell-main-name
s3-stemcell-bucket
s3-stemcell-region-name
s3-stemcell-access-key-id
s3-stemcell-secret-key
s3-stemcell-endpoint
s3-stemcell-skip-ssl-verification

pipeline(depls): move stemcell support from bosh.io to S3

---

concourse/tasks/post_bosh_deploy.yml
spec/tasks/post_bosh_deploy/task_spec.rb

To be able to use other tools based on dynamically linked binary, we
switch to cf-cli image. Indeed, it doesn't work with curl-ssl container
because Alpine uses musl-libc.
The `libc6-compat` package provides `ld-linux-x86-64.so.2` which enables
glibc linked binaries to work. Another commit will follow to make this
work for 64bit binaries on Alpine <= 3.5
See https://github.com/alphagov/paas-docker-cloudfoundry-tools/commits/master/cf-cli/Dockerfile

task(post_bosh_deploy): switch to cf-cli image

---

Readme.md
concourse/pipelines/template/depls-pipeline.yml.erb
concourse/tasks/bosh_update_cloud_config.yml
concourse/tasks/bosh_update_cloud_config/run.sh
concourse/tasks/bosh_update_runtime_config.yml
concourse/tasks/bosh_update_runtime_config/run.sh
concourse/tasks/generate-manifest.yml
scripts/manifest/manifest-lifecycle-generation.sh
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/tasks/bosh_update_cloud_config/task_spec.rb
spec/tasks/bosh_update_runtime_config/task_spec.rb
spec/tasks/generate_manifest/additional-resource/template-with-iaas/another_file.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/gcp/my-gcp-iaas-operators.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/gcp/my-gcp-iaas-tpl.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/gcp/my-gcp-iaas-vars-tpl.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/openstack/iaas-operators.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/openstack/iaas-tpl.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/openstack/iaas-vars-tpl.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/shared-operators.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/shared-tpl.yml
spec/tasks/generate_manifest/additional-resource/template-with-iaas/shared-vars-tpl.yml
spec/tasks/generate_manifest/task_spec.rb

feature: Support ops-files and var-files for [cloud|runtime]-config

---

concourse/pipelines/template/depls-pipeline.yml.erb
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml

To allow pipeline auto update, we introduce a new staging branch called
`pipeline-current-((paas-templates-branch))`.
`update-pipeline-<%= depls %>-generated` job is now scanning
`paas-templates-wip` for changes, is updating pipeline and committing to
`paas-templates-full`. All other jobs are still scanning
`paas-templates-full`. Using this mechanism, reduces dependencies on
`update-pipeline-<%= depls %>-generated`
and reduces inputs.
It should help to fix #19 and #29, but we probably need to introduce a
staging branch for secrets using similar mechanism.
pipeline(depls): only declares bosh-stemcell for `enabled_deployment`
pipeline(depls): migrates to new syntax

pipeline(depls): introduces a new staging branch on paas-templates

---

concourse/tasks/terraform_apply.yml
concourse/tasks/terraform_apply_cloudfoundry.yml
concourse/tasks/terraform_plan_cloudfoundry.yml
spec/tasks/terraform_apply_cloudfoundry/task_spec.rb
spec/tasks/terraform_plan_cloudfoundry/task_spec.rb

We no longer used official image provided by hashicorp. We use a custom
image with all providers already installed, so we don't need internet
access to download providers.
The docker image is a customization of AlphaGov: see [1]
We don't need any reference to terraform-provider-cloudfoundry, as it is
already included in the image.
[1]: https://github.com/orange-cloudfoundry/paas-docker-cloudfoundry-tools/tree/master/terraform

task(terraform_*): switch to custom image with providers and bump TF 0.11.2

---

Readme.md
scripts/manifest/manifest-lifecycle-generation.sh

By convention, all files in template dir matching `*-vars-tpl.yml` are
processed by spruce and generate `*-vars.yml` files.
As spruce is no longer required, it is also possible to include vars
files directly, files matching `*-vars.yml` are used by `bosh-deployment`
but ignored by spruce.

task(generate_manifest): supports vars-file without spruce processing

---

Readme.md
lib/config.rb
scripts/generate-depls.rb
spec/lib/config_spec.rb

we provide a new config mechanism shared across all root deployments. A
default will be provided by cf-ops-automation, but it is possible to
override these values with a `shared-config.yml` file located in
paas-template root directory. It also possible to override again with a
`private-config.yml` file located in secrets root directory.
Usage sample: it will be used to manage offline access (stemcell, bosh
release, docker image, etc...)

script(generate-depls): supports shared config with override

---

concourse/pipelines/template/cf-apps-pipeline.yml.erb
spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-cf-apps.yml

Adds CF info (Api url, org, space, user and password) to post-bosh-deploy
(this is the real name, not the logical one...). Switches to new concourse
pipeline variable declaration (ie ((xx)) instead of  {{xx}})

pipeline(cf-apps): injects CF info as environment variable in post-cf-deploy

---

concourse/pipelines/template/depls-pipeline.yml.erb
concourse/pipelines/template/s3-br-upload-pipeline.yml.erb
concourse/pipelines/template/s3-stemcell-upload-pipeline.yml.erb
lib/template_processor.rb
scripts/generate-depls.rb
spec/lib/template_processor_for_depls_pipeline_spec.rb
spec/lib/template_processor_spec.rb
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-br-upload.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-stemcell-upload.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-br-upload-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-stemcell-upload-ref.yml

We use Boshrelease organisation as upload dir to avoid name collision.
We also triggers init step on creation and regularly for s3-br-upload.
Init step triggers each weekday morning, and this also bump cf-ops-automation
to the latest used version once a day. Otherwise, cf-ops-automation is
stick to an old revision.
Fixes duplicate job in groups.

pipeline(depls,s3-br-upload): supports offline boshrelease and updates boshrelease upload location - REQUIRES shared/private config feature

---

concourse/pipelines/template/cf-apps-pipeline.yml.erb
concourse/pipelines/template/depls-pipeline.yml.erb
concourse/pipelines/template/init-pipeline.yml.erb
concourse/pipelines/template/news-pipeline.yml.erb
concourse/pipelines/template/s3-br-upload-pipeline.yml.erb
concourse/pipelines/template/s3-stemcell-upload-pipeline.yml.erb
concourse/pipelines/template/sync-helper-pipeline.yml.erb
spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-br-upload.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-stemcell-upload.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-init-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-news-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-br-upload-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-stemcell-upload-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-sync-helper-ref.yml

Instead of retrying 3 times on failure, we only retry twice. This is going
to reduce `max_container reach` occurrences. And 3 retries is no more required
as we don't have to much networking issue

pipeline(*): reduce retry number

---

scripts/setUpTfDevEnv.sh

The local dirs that replicate some concourse preprocessing are now done
using hardlinks instead of softlink as docker volumes don't follow
softlinks.
Also illustrated more clearly how to fetch the terraform.tfvars.yml and
draft skeleton to have concourse generate it on the fly.

Update terraform dev env to enable use of docker images used by COA

---

concourse/tasks/terraform_apply_cloudfoundry.yml
concourse/tasks/terraform_plan_cloudfoundry.yml
spec/tasks/terraform_plan_cloudfoundry/task_spec.rb

See [paas-docker-cloudfoundry-tools@74907a778ebecbd9e5d3ff27e210522bffad7047](https://github.com/orange-cloudfoundry/paas-docker-cloudfoundry-tools/commit/74907a778ebecbd9e5d3ff27e210522bffad7047)

task(terraform_*): bump providers (openstack, grafana, credhub and helm)

---

concourse/pipelines/template/depls-pipeline.yml.erb
spec/lib/template_processor/template_processor_for_depls_pipeline_spec.rb

we scan secrets and paas-templates to trigger errand jobs.
Notes: manually triggering deploy job without any changes to repositories
may not trigger errand job.
closes #137

pipeline(depls): fixes errand job triggering

---

.rubocop.yml
concourse/pipelines/template/concourse-pipeline.yml.erb
concourse/pipelines/template/depls-pipeline.yml.erb
concourse/tasks/bosh_interpolate/run.sh
concourse/tasks/bosh_interpolate/task.yml
docs/reference_dataset/template_repository/hello-world/bosh-sample/nginx/template/adding-ntp-release-operators.yml
spec/reference_dataset/reference_dataset_spec.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/scripts/generate-depls/generate_depls_for_depls_pipeline_spec.rb
spec/tasks/bosh_interpolate/task_spec.rb

This PR solves the issue #52  by adding a task for BOSH CLI v2 deployments that will display the manifest with all the operators and vars files included.

Add task displaying manifest before it gets deployed

---

concourse/pipelines/template/tf-pipeline.yml.erb

with #38, this pipeline was left behind, we add the missing environment
variable.
closes #151

pipeline(tf): fixes missing `IAAS_SPEC_PATH`

---

upgrade/v2.2.0/01-upgrade-config.sh

w.r.t. mattermost clean up in config repo
Sample idempotent usage:
```
$ ../cf-ops-automation/scripts/upgrade-2-2.0-config.sh ../int-secrets/
Migrating config repo clone at ../int-secrets/
checking whether upgrade is needed
../int-secrets/kubo-depls/ci-deployment-overview.yml:13:        - micro-depls/concourse-micro/pipelines/credentials-mattermost-certs.yml
../int-secrets/kubo-depls/ci-deployment-overview.yml:25:        - micro-depls/concourse-micro/pipelines/credentials-mattermost-certs.yml
../int-secrets/kubo-depls/ci-deployment-overview.yml:32:        - micro-depls/concourse-micro/pipelines/credentials-mattermost-certs.yml
../int-secrets/kubo-depls/ci-deployment-overview.yml:39:        - micro-depls/concourse-micro/pipelines/credentials-mattermost-certs.yml …
```

Upgrade script for config repo for upcoming release 2.2.0

---

concourse/tasks/git_reset_wip.yml
spec/tasks/git_reset_wip/task_spec.rb

Fixes #173.
- we ensure a new git history is created after reset (also when no feature branches exists)

task(git_reset_wip): create a commit after reset

---

concourse/pipelines/bootstrap-all-init-pipelines.yml
concourse/pipelines/template/bosh-pipeline.yml.erb
concourse/pipelines/template/init-pipeline.yml.erb
concourse/pipelines/template/update-pipeline.yml.erb
concourse/tasks/bootstrap_init_pipelines.yml
concourse/tasks/generate-all-pipelines.yml
concourse/tasks/generate_depls/run.sh
concourse/tasks/generate_depls/task.yml
concourse/tasks/list_used_ci_team/run.rb
lib/ci_deployment.rb
lib/config.rb
lib/pipeline_generator.rb
lib/pipeline_helpers.rb
scripts/concourse-generate-all-pipelines.sh
scripts/concourse-manual-pipelines-update.rb
spec/lib/pipeline_generator_spec.rb
spec/lib/pipeline_helpers_spec.rb
spec/scripts/generate-depls/generate_depls_for_cf_apps_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_depls_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_init_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_news_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_s3_br_upload_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_s3_stemcell_upload_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_for_sync_helper_pipeline_spec.rb
spec/scripts/generate-depls/generate_depls_spec.rb
spec/spec_helper.rb
spec/tasks/all_tasks_spec.rb
spec/tasks/list_used_ci_team/task_spec.rb

Fixes #213.
- we share the same task for init-pipelines and update-pipelines.
- we only generate init or update pipeline in bootstrap instead of all  pipelines. As we support empty vars_files in pipeline definition (ci-deployment-overview.yml) depls-pipeline template is not compatible with this syntax. So we can  generate all pipelines each times.

Fix bootstrap failure on update-pipeline

---

concourse/pipelines/sync-feature-branches.yml
concourse/tasks/git_hard_reset_wip/run.sh
concourse/tasks/git_hard_reset_wip/task.yml
spec/tasks/git_hard_reset_wip/task_spec.rb

Fixes #218.
- add a job to perform a "hard" reset, ie retriggering without change detected.
A simple reset, is not able to detect branch deletion.

pipeline(sync-feature-branches): add hard reset job

---

ci/bootstrap_coa_env/virtualbox/pipeline-vars-prereqs.yml
concourse/pipelines/template/bosh-pipeline.yml.erb
concourse/pipelines/template/depls-pipeline.yml.erb
concourse/pipelines/template/news-pipeline.yml.erb
concourse/pipelines/template/s3-br-upload-pipeline.yml.erb
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/adding-vault-release-operators.yml
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/bosh-deployment-sample-tpl.yml
lib/coa_env_bootstrapper/base.rb
lib/coa_env_bootstrapper/git.rb
lib/coa_env_bootstrapper/runner.rb
spec/lib/coa_env_bootstrapper/git_spec.rb
spec/lib/coa_env_bootstrapper/runner_spec.rb
spec/lib/reference_dataset_documentation/tree_writer_spec.rb
spec/lib/template_processor/template_processor_for_depls_pipeline_spec.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml

Fixes #219, #220 .
- allow user to pass their github token in order the extend the possibility of using the github-release resource without hitting the API requests limit
- fix issue (i.e. make it more consistent) with the way we're using the bosh-io-releases resource.
This PR is still a WIP, since I am still currently testing the second part.

220 github-release resource type

---

concourse/pipelines/bootstrap-all-init-pipelines.yml
concourse/pipelines/micro-bosh-init-pipeline.yml
concourse/pipelines/micro-depls-auto-init.yml
concourse/pipelines/micro-depls-terraform-pipeline.yml
concourse/pipelines/sync-feature-branches.yml
concourse/pipelines/template/cf-apps-pipeline.yml.erb
concourse/pipelines/template/concourse-pipeline.yml.erb
concourse/pipelines/template/depls-pipeline.yml.erb
concourse/pipelines/template/init-pipeline.yml.erb
concourse/pipelines/template/news-pipeline.yml.erb
concourse/pipelines/template/s3-br-upload-pipeline.yml.erb
concourse/pipelines/template/s3-stemcell-upload-pipeline.yml.erb
concourse/pipelines/template/sync-helper-pipeline.yml.erb
concourse/pipelines/template/tf-pipeline.yml.erb
spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb
spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml
spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/empty-depls.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-br-upload.yml
spec/scripts/generate-depls/fixtures/references/empty-s3-stemcell-upload.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-init-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-news-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-br-upload-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-s3-stemcell-upload-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-sync-helper-ref.yml

We generalize proxy support as now we don't need to update each `ci-deployment-overview.yml`
to take into account credentials file
close #148

pipeline(*): support proxy for slack-notification

---

ci/bootstrap_coa_env/pipeline-vars-prereqs.yml
concourse/pipelines/template/concourse-pipeline.yml.erb
concourse/tasks/generate_concourse_pipeline_config/concourse_pipeline_resource_config_generator.rb
concourse/tasks/generate_single_concourse_pipeline_config/concourse_pipeline_resource_config_generator.rb
concourse/tasks/generate_single_concourse_pipeline_config/run.rb
concourse/tasks/generate_single_concourse_pipeline_config/task.yml
docs/reference_dataset/config_repository/coa/config/credentials-usable-by-custom-concourse-pipeline.yml
docs/reference_dataset/template_repository/hello-world-root-depls/pipeline-sample/concourse-pipeline-config/pipeline-sample-tpl.yml
lib/coa/integration_tests/constants.rb
spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb

so it is possible to reuse credentials already defined and its reduce credentials duplication

pipeline(concourse): allow credentials sharing between generated pipelines and custom pipelines

---

concourse/pipelines/template/bosh-pipeline.yml.erb
spec/scripts/generate-depls/fixtures/references/delete-depls-bosh-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml

we trigger on secrets or paas-templates changes.We also remove `at_noon` resource as it was unused
close #262

pipeline(bosh): execute deploy script on each commit

---

docs/reference_dataset/template_repository/hello-world-root-depls/cf-apps-deployments/generic-app/template/generic-app_manifest-tpl.yml

Before fix:
```sh
/tmp/build/a8fceb73 # cat additional-resource/master-depls/osb-cmdb-provisioning/template/files-vars-tpl.yml
---
#manifest_file_content: (( load
deploy_script_file_content: (( file "../../../../additional-resource/master-depls/osb-cmdb-provisioning/template/deploy-ocmdb.bash" ))
/tmp/build/a8fceb73 # ./scripts-resource/concourse/tasks/generate_manifest/generate-manifest.sh
+ spruce --version
spruce - Version 1.14.0
+ pwd
+ CURRENT_DIR=/tmp/build/a8fceb73
+ OUTPUT_DIR=/tmp/build/a8fceb73/generated-files/
+ SPRUCE_SCRIPT_DIR=scripts-resource/concourse/tasks/generate_manifest
+ SUFFIX=-tpl.yml
+ '[' '!' -e ./credentials-resource/master-depls/osb-cmdb-provisioning/secrets/meta.yml ]
+ '[' '!' -e ./credentials-resource/master-depls/osb-cmdb-provisioning/secrets/secrets.yml ] …
```

Fix invalid relative path in reference documentation

---

concourse/tasks/check_configuration/run.sh
spec/tasks/check_config/task_spec.rb

Was:
ERROR: local-secret-scan disabled  in deployment-dependencies.yml for osb-cmdb-provisioning, but config files (meta.yml, secrets.yml) detected at config-resource/master-depls/osb-cmdb-provisioning/secrets
while expected property is `local_deployment_scan` and not `local-secret-scan`
with deployment-dependencies.yml, this fails: 
```yaml
deployment:
osb-cmdb-provisioning:
resources:
releases:
cf-cli:
base_location: https://bosh.io/d/github.com/
repository: bosh-packages/cf-cli-release
errands:
errand-scripting:
```
whith deployment-dependencies.yml deployment is ok
```
deployment:
osb-cmdb-provisioning:
resources:
secrets:
local_deployment_scan: true
releases:
cf-cli:
base_location: https://bosh.io/d/github.com/
repository: bosh-packages/cf-cli-release
errands:
errand-scripting:
```

Improve wording of error message

---

concourse/pipelines/template/bosh-pipeline.yml.erb
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml
lib/pipeline_helpers/deployment_details.rb
scripts/concourse-manual-pipelines-update.rb
spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb

We also use metadata-resource to replace secrets and paas-template resources,
so we are able to trigger errands even on git reset.
close #14, close #285, related to #197

feature(bosh-pipeline): add manual-errand support and multi job errands

---

concourse/pipelines/template/bosh-pipeline.yml.erb
concourse/pipelines/template/news-pipeline.yml.erb
concourse/pipelines/template/s3-br-upload-pipeline.yml.erb
lib/pipeline_generator.rb
spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb

when a boshrelease is declared in `deployment-dependencies.yml`, another
deployment cannot override the definition anymore.

feature(bosh-pipelines): detect inconsistent boshrelease detect-inconsistent-boshrelease-definitions

---

concourse/pipelines/template/bosh-pipeline.yml.erb
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml
spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb

By default, errands are named 'run-errand-<deployment-name>-<errand-name>', unless a `display-name` is set in errand definition in deployment-dependencies.yml. When `display-name` is set, name is 'run-errand-<deployment-name>-<display-name>'
close #296

feature(bosh-pipeline): support errand name customization

---

concourse/pipelines/bootstrap-all-init-pipelines.yml

instead of using a predetermined credentials list. We encounter this issue after removing `credentials-docker-registry.yml`

fix(bootstrap-all-init-pipeline): auto detect credentials files

---

concourse/tasks/bosh_delete_apply/delete_apply.rb
spec/tasks/bosh_delete_apply/delete_apply_spec.rb

to avoid leaks, we choose to ignore errors on bosh delete, so we can delete as much deployments as possible and we get all errors at the end.

feature(bosh-delete-deployment): fail-slow, to delete as much deployments as possible

---

concourse/pipelines/bootstrap-all-init-pipelines.yml
lib/coa/integration_tests/constants.rb
scripts/concourse-bootstrap.sh

Curl is not included in `governmentpaas/bosh-cli-v2` image, so we switch to wget, as it is embedded in image.
We broke this task when we swtiched to this image (from `governmentpaas/curl-ssl`).
We also include `reload-this-pipeline-from-git` in `integration-tests`

fix(bootstrap-all-init-pipeline): replace curl by wget

---

concourse/pipelines/template/bosh-pipeline.yml.erb
concourse/tasks/git_update_a_file_from_generated.yml
spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb

Fixes #323.
- update commit message to ensure concourse detected it
- support interpretation of backslash escapes in commit messages

Fix tfstate change detection

---

concourse/tasks/bosh_update_config/run.sh

Credhub won't error on missing variable, it is going to fail during `bosh deployment` step
close #331

feature(allow-incomplete-crehub-interpolation):

---

concourse/pipelines/bootstrap-all-init-pipelines.yml
concourse/pipelines/control-plane.yml
concourse/pipelines/template/bosh-pipeline.yml.erb
concourse/pipelines/template/concourse-pipeline.yml.erb
lib/coa/integration_tests/constants.rb
spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb
spec/scripts/generate-depls/fixtures/references/empty-concourse.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml

feature(multi-concourse-version-compliant-pipelines): update pipelines to be able to run it on concourse 5.8.x and concourse 6.4.x
It seems concourse 6.4 do some checks on resource get params and it fails if unexpected params are detected.
We need to support two concourse-pipeline resources as authentication between concourse 5.8.1 and 6.4.x are not compatible.  
So we add dual mode to reach concourse, as concourse 6 is the target version, we first try to deploy on v6 and only on failure we try on v5. As when there is a failure, build stop we need to use a `try` step to allow failure, and we need a way to detect success as `try` step always succeed. We use `on_success`, as it seems only triggered when `try` step succeed.

feature(multi-concourse-version-compliant-pipelines): update pipelines to be able to run it on concourse 5.8.x and concourse 6.4.x

---

ci/pipeline.yml
concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
docs/reference_dataset/config_repository/hello-world-root-depls/ci-deployment-overview.yml
lib/coa/integration_tests/constants.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml

The default team in this pipeline is '<root-deployment-name>' unless it is 'main' in other pipelines. This is required as this pipeline in not loaded as others pipelines, it loaded by upgrade pipeline, not describe in `ci-deployment-overview.yml`.
We also use teams in out IT.

pipeline(bosh-precompile): fix pipeline team

---

concourse/pipelines/sync-feature-branches.yml

As we need to manually checkout git repository in this pipeline, we need to support skip ssl check on git repo

pipeline(sync-feature-branches): fix missing untrusted certificates support

---

concourse/tasks/resolve_manifest_versions/resolve_manifest_versions.rb
spec/tasks/resolve_manifest_versions/resolve_manifest_versions_spec.rb

Specs implemented to resolve manifest versions (bosh releases and stemcells):
*   when valid versions and manifest are provided, locks all boshreleases and stemcells
*   when version are not managed by COA,      ignores boshreleases and stemcell versions
*   when latest is used as version,      keeps latest versions
*   when no stemcell version is defined,      raises an error
*   when manifest does not use 'latest' as version,      overrides boshreleases versions and keeps stemcell versions
*   when multiple stemcells are defined in manifest,      locks all boshreleases and stemcells versions matching 'os' or without 'os' set
*   when multiple stemcells with different os are defined in manifest,      ignores stemcell that does not match defined 'os'

fix(resolve-manifest-version): handle properly multiple stemcell definition

---

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
concourse/tasks/resolve_manifest_versions/resolve_manifest_versions.rb
docs/reference_dataset/config_repository/private-config.yml
docs/reference_dataset/template_repository/shared-config.yml
lib/deployment.rb
lib/deployment_deployers_config.rb
lib/root_deployment.rb
spec/lib/template_processor/template_processor_for_bosh_precompile_pipeline_spec.rb

- we do not filter on deployment state to determine when to include dependencies
We do not use secret repository to determine which deployment we need to proccess, we scan every deployments for dependencies.
it still possible to exclude some deployments using `shared-confg.yml` and `private-config.yml`, by setting properties below:
```
<root-deployment-name>:
precompile:
excluded_deployments: [] # Default: [] # List deployments to exclude
from precompilation. As precompilation does not use secrets repository to
determine enabled deployments, it might be convenient to exclude a
deployment not enanled in secrets.
```

pipeline(bosh-precompile): only use templates to generate pipeline

---

ci/pipeline.yml
concourse/pipelines/template/k8s-pipeline.yml.erb
concourse/tasks/apply_iaas_type_and_profiles/run.sh
concourse/tasks/apply_iaas_type_and_profiles/task.yml
concourse/tasks/execute_k8s_shells/run.sh
concourse/tasks/execute_k8s_shells/task.yml
docs/reference_dataset/template_repository/hello-world-root-depls/hooks/k8s/deploy.sh
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/01-interpolate.sh
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/02-deploy.sh
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/config.yml
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/openstack/values-iaas-type.yml
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/post-deploy.sh
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/pre-deploy.sh
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/values.yml
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/vault-profile/custom-dir/vault-config.yml
docs/reference_dataset/template_repository/hello-world-root-depls/k8s-sample/k8s-config/vault-profile/values-profile.yml
lib/coa/integration_tests/constants.rb
lib/coa/utils/command_runner.rb
spec/tasks/all_tasks_spec.rb
spec/tasks/apply_iaas_type_and_profiles/task_spec.rb
spec/tasks/execute_k8s_shells/task_spec.rb
spec/tasks/execute_k8s_shells/templates_dir_fixture/my-root-depls/my-deployment/my-config/00-profile-p1-script.sh
spec/tasks/execute_k8s_shells/templates_dir_fixture/my-root-depls/my-deployment/my-config/00-profile-p3-script.sh
spec/tasks/execute_k8s_shells/templates_dir_fixture/my-root-depls/my-deployment/my-config/01-iaas-script.sh
spec/tasks/execute_k8s_shells/templates_dir_fixture/my-root-depls/my-deployment/my-config/a-script.sh
spec/tasks/execute_k8s_shells/templates_dir_fixture/my-root-depls/my-deployment/my-config/dummy-iaas/01-iaas-script.sh
spec/tasks/execute_k8s_shells/templates_dir_fixture/my-root-depls/my-deployment/my-config/p1/00-profile-p1-script.sh
spec/tasks/task_spec_helper.rb

- fix pipeline without deployment
- externalize k8s tasks to ease manual rerun on fly hijack
- rework scripts support:
- root-deployments level scripts should be located in `<root-deployments-name>/hooks/k8s`, instead of `<root-deployments-name>/template`
- execute scripts matching `pre-deploy*.sh`, `deploy*.sh` or `post-deploy*.sh`, according to the current step

feature(minimal-kubernetes-support): fix pipeline without deployment

---

docs/reference_dataset/template_repository/hello-world-root-depls/cf-apps-deployments/generic-app/template/cf-env.sh
scripts/cf/push.sh

With cf cli v7 support, we switch to "rolling strategy" to avoid application downtime. But "--strategy" in not compliant with "-f" option when manifest includes multiple app definitions. So we add a mechanism to override cf push default parameters.
Fixes #240.

feature(tune-cf-push-options): allow cf push customization

---

Dockerfile
docs/reference_dataset/template_repository/hello-world-root-depls/pipeline-sample/concourse-pipeline-config/pipeline-sample-tpl.yml
lib/coa/utils/concourse/build.rb
lib/coa/utils/concourse/fly.rb
spec/lib/coa/utils/concourse/build_spec.rb

- upgrade concourse to latest version (7.2)
- adapt IT to new cli output (switch to json output)
This PR replaces and closes #364

Concourse 7.2 bump

---

docs/reference_dataset/template_repository/hello-world-root-depls/cf-apps-deployments/generic-app/template/generic-app_manifest-tpl.yml
docs/reference_dataset/template_repository/hello-world-root-depls/cf-apps-deployments/generic-app/template/pre-cf-push.sh

Suse standboxes sunsets, so we need to use another CF plateform. Ibm Cloud offers a free plan, so we migrate to it.
We need to use a random route as our route is already in-use. It not possible to use 'set-space-role' command, so we remove it.

test(integration-tests): switch to ibm cloud

---

Dockerfile

Requesting a pull to orange-cloudfoundry:develop from orange-cloudfoundry:enforce-empty-sha1-for-compiled-releases
Write a message for this pull request. The first block
of text is the title and the rest is the description.

chore(ci): update test image to concourse 7.3.2

---

concourse/pipelines/template/bosh-pipeline.yml.erb
concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
concourse/pipelines/template/cf-apps-pipeline.yml.erb
concourse/pipelines/template/concourse-pipeline.yml.erb
concourse/pipelines/template/k8s-pipeline.yml.erb
concourse/pipelines/template/news-pipeline.yml.erb
concourse/pipelines/template/tf-pipeline.yml.erb
concourse/pipelines/template/update-pipeline.yml.erb
docs/reference_dataset/template_repository/shared-config.yml
lib/config.rb
lib/pipeline_helpers.rb
lib/pipeline_helpers/configured_concourse_retry.rb
lib/pipeline_helpers/configured_git_shallow_clone_depth.rb
lib/pipeline_helpers/pipeline_configurer.rb
spec/lib/config_spec.rb
spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml
spec/scripts/generate-depls/fixtures/references/delete-depls-bosh-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-k8s-ref.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-news-ref.yml
spec/scripts/generate-depls/fixtures/templates/shared-config.yml

We can tune the number of concourse retries in multiple cases. When not specified, it will use values below:
```
default:
retry: # Configure how to handle retries in various context
task: 2 # Optional. You may override number of retry when running concourse tasks (except put, get and bosh deploy)
pull: 2 # Optional. You may override number of retry when getting data from external system like git, s3, etc...
push: 2 # Optional. You may override number of retry when sending data to external system like git, s3, etc...
bosh-push: 2 # Optional. You may override number of retry when sending data to bosh
```
But you can override default value using `paas-templates/shared-config.yml` or `secrets/private-config.yml`.

feature(configure-concourse-retry): enhance concourse retry management

---

concourse/pipelines/control-plane.yml
concourse/pipelines/template/update-pipeline.yml.erb
concourse/tasks/git_append_a_dir_from_generated/task.yml
spec/pipelines/static_pipelines_spec.rb
spec/tasks/task_spec_helper.rb

- use `fly format-pipeline` command to format generated or deployed pipelines

pipelines(control-plane|update): use fly to format pipelines

---

concourse/pipelines/template/bosh-pipeline.yml.erb
spec/pipelines/static_pipelines_spec.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml

We remove git commit message from bosh tags, to avoid issues with unexpected characters included in commit messages.
It may generate Flexible Engine (openstack iaas) tag API burst on WIP recreate.
Related to orange-cloudfoundry/paas-templates#1435 (bosh: too many tag update request)
- do not include commit message in tags

pipelines(bosh): remove commit message from bosh tags

---

concourse/pipelines/template/bosh-pipeline.yml.erb
spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml

Paas-template resources include meta-inf.yml in scan path, except for paas-templates-full (already included) and paas-templates-<xxx>-versions dedicated to 'root-deployment.yml' file
related to orange-cloudfoundry/paas-templates#1366.

pipeline(bosh): fix meta-inf.yml detection

---

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
spec/lib/template_processor/template_processor_for_bosh_precompile_pipeline_spec.rb

To determine when a bosh release need to be compiled, we only search for repository and version, and ignores any others data.
Previously, we did not detect bosh release compiled by parent due to sha1.

pipeline(precompile): fix already compile bosh release detection

---

Readme.md
concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
docs/BoshReleases_upload.puml
docs/COA-Mechanisms.md
docs/Readme.md
docs/Stemcell_upload.puml
spec/lib/template_processor/template_processor_for_bosh_precompile_pipeline_spec.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml

when no precompile releases are available (due to cache mechanism, or there is nothing to compile), we still need `push-boshrelease` step to ensure bosh-releases related to runtime-config are processed.
Related to orange-cloudfoundry/paas-templates#1888

pipeline(precompile): fix missing release upload without precompile

---

concourse/pipelines/template/bosh-pipeline.yml.erb
docs/reference_dataset/config_repository/private-config.yml
docs/reference_dataset/template_repository/shared-config.yml

With jammy stemcell we encounter incompatible bosh releases, so we want to keep the old stemcell and still have minimal management by COA, without adding multi stemcell support.
See https://github.com/orange-cloudfoundry/cf-ops-automation/blob/e59a0a2fdef16aeb3874ec590edafbb05d36da03/docs/reference_dataset/template_repository/shared-config.yml#L63-L64
* Used stemcell should be upload to bosh director by other mean,
* Bosh releases handled by COA (ie described in `root-deployment.yml` and `deployment-dependecies.yml`), must be compiled with active stemcell.

pipeline(bosh): fine grain management of compiled download url

---

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml

To avoid corrupted compiled releases use, we need to check errors occurring during precompile. Once a related error is detected, we delete existing deployment and release, without force option.
related orange-cloudfoundry/paas-templates#2022

pipeline(precompile): detect blobstore related errors

---

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
spec/lib/template_processor/template_processor_for_bosh_precompile_pipeline_spec.rb
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml

It seems that we lost this improvement when we introduced the "shared" pipeline support. Hence, we are renaming, again, the BOSH deployment that is used by precompile to ensure easy identification.

feature(easily-identify-precompile-deployments): restore this feature

---

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
docs/reference_dataset/config_repository/private-config.yml
docs/reference_dataset/template_repository/shared-config.yml
spec/scripts/generate-depls/fixtures/references/empty-bosh-precompile.yml
spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml

Add a parameter to allow some bosh releases to be recompiled on some bosh directors
```
<root-deployment-name>:
precompile:
disabled-cached-releases: [] # Default: [] - List of bosh releases to compile on local bosh director, even when compiled
```
Related to https://github.com/orange-cloudfoundry/paas-templates/issues/2022

pipeline(precompile): allow configuration to force local compilation on bosh director

---

concourse/tasks/repackage_boshreleases_fallback/repackage_releases_fallback.rb
spec/tasks/repackage_boshreleases_fallback/bosh_connection_refused/errors.yml
spec/tasks/repackage_boshreleases_fallback/repackage_releases_fallback_spec.rb

As of Ruby 3.1, if you use YAML.load_file, you must explicitly list the classes that are allowed for deserialization.
Otherwise, a `Psych::DisallowedClass` error will be thrown.
Fixes #442
- add BoshCliError to allowed classes for deserilization
- add test to illustrate the error

tasks(repackage_boshreleases_fallback): fix deserialization

---

concourse/tasks/cf_push.yml
concourse/tasks/post_bosh_deploy.yml
concourse/tasks/post_deploy/run.sh
concourse/tasks/pre_deploy/run.sh
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/check-available-clis-during-deploy.sh
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/post-deploy.sh
docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/pre-deploy.sh
scripts/cf/push.sh
spec/tasks/all_tasks_spec.rb
spec/tasks/apply_iaas_type_and_profiles/task_spec.rb
spec/tasks/bosh_update_config/cloud_config_spec.rb
spec/tasks/bosh_update_config/cpi_config_spec.rb
spec/tasks/bosh_update_config/runtime_config_spec.rb
spec/tasks/execute_deploy_script/task_spec.rb
spec/tasks/post_deploy/task_spec.rb
spec/tasks/task_spec_helper.rb

- use bosh-cli-v2-cf-cli image instead of cf-cli image

Include bosh cli in post deploy
