ci/pipeline.yml
as to avoid code injection into the test pipeline
=> Only accept PRs from the original repo

concourse/tasks/terraform_apply_cloudfoundry.yml, concourse/tasks/terraform_plan_cloudfoundry.yml
As this freezes jobs execution until a human kills them.
=> Don't allow TF to prompt for user input 

concourse/pipelines/template/depls-pipeline.yml.erb
Map the secret full resource to enable tf cross reference tf states
https://www.terraform.io/docs/providers/terraform/d/remote_state.html
=> Map the secret full resource to enable tf cross reference tf state

Dockerfile, Gemfile.lock, ci/pipeline.yml, concourse/pipelines/template/depls-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml, spec/tasks/terraform_apply_cloudfoundry/task_spec.rb, spec/tasks/terraform_plan_cloudfoundry/task_spec.rb
without task variable args, we are able to extract task config into a
dedicated yaml file:
- to have independent testable task
- to reduce pipeline verbosity
=> pipeline(depls): refactor to extract task variable args into task params

concourse/pipelines/template/tf-pipeline.yml.erb
removed secrets-full and only uses secrets-<%=depls %>
=> Fix improper input mapping for secrets in tf-pipeline

concourse/pipelines/template/depls-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml, spec/scripts/generate-depls/fixtures/references/empty-depls.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
We have to switch to latest concourse/bosh-deployment-resource version
close #53
=> pipeline(depls): overrides bosh-deployment-resource v1 to latest

concourse/pipelines/template/depls-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml, spec/scripts/generate-depls/fixtures/references/empty-depls.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
`secrets-full-writer` is a new shared resource used by all jobs to commit
any changes to the `secrets` repository. We hopes we can share the same
resource across jobs.
closes #74
=> pipeline(depls): add new resource to handle git commit

concourse/pipelines/template/depls-pipeline.yml.erb
We use secrets-<%=depls%> and paas-template-<%=depls%> instead of
<secrets|paas-template>-full
=> pipeline(depls): restores terraform scan during update-pipeline

concourse/pipelines/template/cf-apps-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml
This PR solves the following issue: #123
=> add value 'serial: true' to cf-push-app job in cf-apps-pipeline

.gitignore, Readme.md, lib/config.rb, lib/deployment.rb, lib/deployment_factory.rb, lib/root_deployment_version.rb, scripts/generate-depls.rb, spec/lib/config_spec.rb, spec/lib/deployment_factory_spec.rb, spec/lib/deployment_spec.rb, spec/lib/root_deployment_version_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-depls-s3-stemcell-upload-ref.yml, spec/scripts/generate-depls/fixtures/templates/apps-depls/apps-depls-versions.yml, spec/scripts/generate-depls/fixtures/templates/delete-depls/bosh/deployment-dependencies.yml, spec/scripts/generate-depls/fixtures/templates/delete-depls/delete-depls-versions.yml, spec/scripts/generate-depls/fixtures/templates/no-dependency-depls/bosh/deployment-dependencies.yml, spec/scripts/generate-depls/fixtures/templates/no-dependency-depls/no-dependency-depls-versions.yml, spec/scripts/generate-depls/fixtures/templates/shared-config.yml, spec/scripts/generate-depls/fixtures/templates/simple-depls/ntp/deployment-dependencies.yml, spec/scripts/generate-depls/fixtures/templates/simple-depls/simple-depls-versions.yml, upgrade/v2.0.0/01-upgrade-paas-template.rb
=> WIP - Move out stemcell declararation from deployment-dependencies.yml

concourse/tasks/terraform_apply_cloudfoundry.yml, concourse/tasks/terraform_plan_cloudfoundry.yml, spec/tasks/terraform_plan_cloudfoundry/task_spec.rb
we use the new terraform image with libc6-compat
=> task(terraform_*):fix helm terraform provider

concourse/pipelines/template/depls-pipeline.yml.erb, concourse/tasks/bosh_delete_apply/run.sh, concourse/tasks/bosh_delete_apply/task.yml, concourse/tasks/bosh_delete_plan/run.rb, concourse/tasks/bosh_delete_plan/task.yml, spec/scripts/generate-depls/fixtures/references/delete-depls-ref.yml, spec/scripts/generate-depls/generate_depls_for_depls_pipeline_spec.rb, spec/tasks/bosh_delete_apply/task_spec.rb, spec/tasks/bosh_delete_plan/task_spec.rb, spec/tasks/task_spec_helper.rb
=> pipeline(depls): collapse delete task to speed up concourse execution

Readme.md, concourse/tasks/git_update_all_files_from_generated.yml, docs/reference_dataset/template_repository/another-world-root-depls/another-bosh-deployment-sample/deployment-dependencies.yml, docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml, docs/reference_dataset/template_repository/hello-world-root-depls/cf-apps-deployments/generic-app/deployment-dependencies.yml, docs/reference_dataset/template_repository/hello-world-root-depls/pipeline-sample/deployment-dependencies.yml, lib/deployment.rb, lib/deployment_factory.rb, lib/directory_initializer.rb, lib/root_deployment.rb, scripts/init-template.sh, spec/lib/deployment_factory_spec.rb, spec/lib/root_deployment_spec.rb, spec/scripts/generate-depls/fixtures/templates/no-dependency-depls/bosh/deployment-dependencies.yml, spec/scripts/generate-depls/fixtures/templates/simple-depls/ntp/deployment-dependencies.yml
- allow usage of generic key in deployment-dependencies
- update reference dataset
-
=> allow usage of generic key in deployment-dependencies

ci/pipeline.yml, concourse/pipelines/template/depls-pipeline.yml.erb, docs/reference_dataset/config_repository/private-config.yml, docs/reference_dataset/template_repository/shared-config.yml, scripts/concourse-manual-pipelines-update.rb, spec/lib/template_processor/template_processor_for_depls_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml
Fixes #128.
- By default, we use offline stemcell, but it can be overridden by `shared-config.yml` or `private-config.yml`
=> Online stemcells support

concourse/pipelines/bootstrap-all-init-pipelines.yml, concourse/pipelines/micro-bosh-init-pipeline.yml, concourse/pipelines/micro-depls-auto-init.yml, concourse/pipelines/micro-depls-terraform-pipeline.yml, concourse/pipelines/ops-depls-terraform-pipeline.yml, concourse/pipelines/template/cf-apps-pipeline.yml.erb, concourse/pipelines/template/concourse-pipeline.yml.erb, concourse/pipelines/template/depls-pipeline.yml.erb, concourse/pipelines/template/init-pipeline.yml.erb, concourse/pipelines/template/s3-br-upload-pipeline.yml.erb, concourse/pipelines/template/s3-stemcell-upload-pipeline.yml.erb, spec/helpers/utils.rb, spec/lib/config_spec.rb, spec/lib/deployment_deployers_config_spec.rb, spec/lib/deployment_factory_spec.rb, spec/lib/deployment_spec.rb, spec/lib/directory_initializer_spec.rb, spec/lib/git_modules_spec.rb, spec/lib/pipeline_generator_spec.rb, spec/lib/root_deployment_spec.rb, spec/lib/root_deployment_version_spec.rb, spec/lib/template_processor/template_processor_for_cf_apps_pipeline_spec.rb, spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb, spec/lib/template_processor/template_processor_for_depls_pipeline_spec.rb, spec/lib/template_processor/template_processor_spec.rb, spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml, spec/scripts/generate-depls/fixtures/secrets/apps-depls/my_cf_app/enable-cf-app.yml, spec/scripts/generate-depls/generate_depls_for_cf_apps_pipeline_spec.rb
This PR present a holistic solution to handle special characters that may be passed to the concourse pipelines.
Moreover, it makes a few non-incidental changes to the code to make it more idiosyncratic with the help of rubocop.
Fixes #145.
=> 145 yaml passwords

concourse/tasks/terraform_apply_cloudfoundry.yml, concourse/tasks/terraform_plan_cloudfoundry.yml
Minor internal documentation (docker image source)
=> Document source of docker image used for terraform

concourse/pipelines/template/depls-pipeline.yml.erb, concourse/tasks/bosh_variables/bosh_variables_executor.rb, concourse/tasks/bosh_variables/run.rb, concourse/tasks/bosh_variables/task.yml, scripts/concourse-bootstrap.sh, spec/scripts/generate-depls/fixtures/references/simple-depls-ref.yml, spec/tasks/bosh_variables/bosh_variables_spec.rb, spec/tasks/bosh_variables/task_spec.rb, spec/tasks/execute_deploy_script/task_spec.rb
Fixes #72.
- scripts(concourse-bootstrap): remove useless IAAS_TYPE variable
- task(execute_deploy_script): add pre-requisite tests
- task(bosh_variables): get variable fingerprints for a deployment
- pipeline(depls): levrage bosh_variables task
=> bosh config server / credhub variables fingerprint

lib/concerns/coa_logger.rb
- changing the logger utils module so that we can now use it in class methods
=> logger(*): fix the logger so that it works for class methods.

lib/pipeline_helpers.rb, spec/lib/pipeline_helpers_spec.rb
For when no submodules is declared for a deployment which root deployment has submodules
=> pipelines(submodules): fix 

concourse/tasks/bosh_update_cloud_config/run.sh, concourse/tasks/bosh_update_runtime_config/run.sh, spec/tasks/bosh_update_cloud_config/task_spec.rb, spec/tasks/bosh_update_runtime_config/task_spec.rb
=> tasks(bosh_update_[cloud|runtime]_config: fix operator alphabetical order when applied

concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/tasks/bosh_update_cloud_config.yml, concourse/tasks/bosh_update_cloud_config/run.sh, concourse/tasks/bosh_update_runtime_config.yml, concourse/tasks/bosh_update_runtime_config/run.sh
this also require an update of underlying tasks (bosh_update_[cloud|runtime]_config)
fix #246 (committed generated cloud-config.yml and runtime-config.yml are incomplete)
fix #2
=> pipeline(bosh): improvements

concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/tasks/bosh_cancel_all_tasks/task.yml, concourse/tasks/bosh_delete_apply/task.yml, concourse/tasks/bosh_interpolate/task.yml, concourse/tasks/bosh_update_config/task.yml, concourse/tasks/bosh_variables/task.yml, concourse/tasks/cf_push.yml, concourse/tasks/check_configuration/task.yml, concourse/tasks/execute_deploy_script.yml, concourse/tasks/generate-manifest.yml, concourse/tasks/post_bosh_deploy.yml, docs/reference_dataset/template_repository/hello-world-root-depls/pipeline-sample/concourse-pipeline-config/docker-image-vars.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/tasks/task_spec_helper.rb
=> feature(cf-app): bump cf cli version

Readme.md, concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/concourse-pipeline.yml.erb, docs/reference_dataset/pipelines/hello-world-root-depls-bosh-generated.yml, docs/reference_dataset/pipelines/hello-world-root-depls-concourse-generated.yml, docs/script-lifecycle-overview.puml, spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/scripts/generate-depls/generate_depls_for_bosh_pipeline_spec.rb, spec/tasks/pre_deploy/task_spec.rb
=> feature(remove-spiff-references): as spiff image is not used anymore, it is not required to keep such references

concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/tasks/bosh_variables/bosh_variables_executor.rb, concourse/tasks/git_update_a_dir_from_generated.yml, concourse/tasks/git_update_a_file_from_generated.yml, concourse/tasks/git_update_all_files_from_generated.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/tasks/bosh_variables/bosh_variables_spec.rb, spec/tasks/bosh_variables/task_spec.rb
- add bosh deployment information to bosh variable git commit
=> feature(display-bosh-deployment-information)

concourse/pipelines/template/bosh-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml
=> pipeline(bosh): add retry on secrets repository push

concourse/pipelines/bootstrap-all-init-pipelines.yml, concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/cf-apps-pipeline.yml.erb, concourse/pipelines/template/concourse-pipeline.yml.erb, concourse/pipelines/template/news-pipeline.yml.erb, concourse/pipelines/template/s3-br-upload-pipeline.yml.erb, concourse/pipelines/template/s3-stemcell-upload-pipeline.yml.erb, concourse/pipelines/template/sync-helper-pipeline.yml.erb, concourse/pipelines/template/tf-pipeline.yml.erb, concourse/pipelines/template/update-pipeline.yml.erb, docs/reference_dataset/config_repository/private-config.yml, docs/reference_dataset/template_repository/shared-config.yml, lib/config.rb, lib/pipeline_helpers.rb, lib/pipeline_helpers/configured_git_shallow_clone_depth.rb, lib/pipeline_helpers/pipeline_configurer.rb, spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml, spec/scripts/generate-depls/fixtures/references/delete-depls-bosh-ref.yml, spec/scripts/generate-depls/fixtures/references/empty-depls.yml, spec/scripts/generate-depls/fixtures/references/empty-s3-br-upload.yml, spec/scripts/generate-depls/fixtures/references/empty-s3-stemcell-upload.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-news-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-s3-br-upload-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-s3-stemcell-upload-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-sync-helper-ref.yml, spec/scripts/generate-depls/generate_depls_for_bosh_pipeline_spec.rb
we try to clone only latest commit instead of the whole repo
=> feature(git-shallow-clone): change git resource configuration to reduce git server workload

concourse/pipelines/template/bosh-pipeline.yml.erb, docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml, lib/pipeline_helpers/deployment_details.rb, spec/lib/pipeline_helpers/deployment_details_spec.rb, spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml
We also implement git depth override per deployment (it still may be ovveride per root deployment).
=> feature(disable-recursive-submodule-checkout): implements this feature for bosh pipelines

concourse/tasks/check_configuration/run.sh
add a message to identify when shared-secrets triggering is activated or not.
=> feature: ease shared secrets triggering debug

ci/tasks/run-ITs/task.yml, concourse/pipelines/bootstrap-all-init-pipelines.yml, concourse/pipelines/control-plane.yml, concourse/pipelines/sync-feature-branches.yml, concourse/pipelines/template/bosh-precompile-pipeline.yml.erb, concourse/pipelines/template/concourse-pipeline.yml.erb, concourse/tasks/repackage_boshreleases_fallback/task.yml, lib/coa/integration_tests/constants.rb, scripts/generate-and-load-pipeline.sh, spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/empty-bosh-precompile.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml
to avoid race condition on single deployment, we use several dedicated deployment
=> pipeline(bosh-precompile): split single deployment into dedicated deployments

ci/bootstrap_coa_env/inactive-steps-prereqs.yml, ci/pipeline.yml, ci/run-manual-ITs.sh, concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/bosh-precompile-pipeline.yml.erb, concourse/tasks/s3_stemcells_upload/task.yml, docs/reference_dataset/template_repository/hello-world-root-depls/template/openstack/disk-types-cloud-operators.yml, docs/reference_dataset/template_repository/hello-world-root-depls/template/public-config-operators.yml, docs/reference_dataset/template_repository/hello-world-root-depls/template/public-runtime-operators.yml, lib/coa/env_bootstrapper/bosh.rb, lib/coa/integration_tests/constants.rb, spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb, spec/lib/template_processor/template_processor_for_bosh_precompile_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/delete-depls-bosh-ref.yml, spec/scripts/generate-depls/fixtures/references/empty-bosh-precompile.yml, spec/scripts/generate-depls/fixtures/references/empty-depls.yml, spec/scripts/generate-depls/fixtures/references/empty-k8s.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-k8s-ref.yml
To avoid freeze on bosh director during precompile we introduce a single point of upload for stemcell.
=> pipelines(bosh|precompile): rework stemcell upload

ci/pipeline.yml, concourse/pipelines/bootstrap-all-init-pipelines.yml, concourse/pipelines/micro-bosh-init-pipeline.yml, concourse/pipelines/micro-depls-terraform-pipeline.yml, concourse/pipelines/template/concourse-pipeline.yml.erb, concourse/pipelines/template/news-pipeline.yml.erb, spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/empty-news.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-news-ref.yml, spec/tasks/task_spec_helper.rb
- avoid use of 'latest' for docker image
- fix concourse pipeline triggering on secrets/coa/config
-
=> avoid usage of latest tag for docker image

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml
We introduce the same mechanism used in bosh pipeline, ie serial_group. Same advantages and drawbacks...
Fixes #372
=> feature(rate-limiting-on-bosh-release-precompile):

Dockerfile, concourse/pipelines/sync-feature-branches.yml, concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/cf-apps-pipeline.yml.erb, concourse/pipelines/template/concourse-pipeline.yml.erb, concourse/pipelines/template/update-pipeline.yml.erb, concourse/tasks/bosh_upload_stemcell/task.yml, concourse/tasks/generate_concourse_pipeline_config/concourse_pipeline_resource_config_generator.rb, docs/reference_dataset/pipelines/hello-world-root-depls-bosh-generated.yml, docs/reference_dataset/template_repository/hello-world-root-depls/root-deployment.yml, spec/lib/template_processor/template_processor_for_bosh_pipeline_spec.rb, spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb, spec/lib/template_processor/test_fixtures/resource_fixture.rb, spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml, spec/scripts/generate-depls/fixtures/references/delete-depls-bosh-ref.yml, spec/scripts/generate-depls/fixtures/references/empty-depls.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/scripts/generate-depls/generate_depls_for_bosh_pipeline_spec.rb, spec/tasks/git_append_a_dir_from_generated/task_spec.rb, spec/tasks/git_update_a_dir_from_generated/task_spec.rb, spec/tasks/git_update_a_file_from_generated/task_spec.rb
Related to:
- https://github.com/orange-cloudfoundry/paas-templates/issues/1366
- https://github.com/orange-cloudfoundry/paas-templates/issues/1367
* **pipelines(update,concourse,cf-apps): fix missing scanned files**
* chore(ci): bump to concourse 7.6.0 and bosh-cli 6.4.7
* doc(reference-dataset): bump stemcell and bosh releases
* pipelines(bosh): inject git info into bosh manifest (author, message, sha1). Close #381
* pipelines(sync-feature-branches): 
* increase merge.renamelimit
* add retry mechanism for merge-commit task
=> fix missing scanned files and concourse bump

concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/bosh-precompile-pipeline.yml.erb, spec/pipelines/static_pipelines_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/tasks/task_spec_helper.rb
use to spruce to inject commit message. Using spruce escape bahs characters.
=> pipelines(bosh): fix git info into bosh manifest injection

concourse/tasks/bosh_upload_releases/task.yml, concourse/tasks/bosh_upload_stemcell/task.yml
- detect upload failure, and raise an error accordingly
=> tasks(bosh_upload_stemcell): detect errors during stemcell upload

concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/concourse-pipeline.yml.erb, docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/bosh-deployment-sample-tpl.yml, spec/lib/template_processor/template_processor_for_concourse_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml
- ensure coa metadata are available as bosh variables in bosh manifest
=> feature(bosh-pipeline): inject coa-metadata

concourse/pipelines/template/bosh-pipeline.yml.erb, concourse/pipelines/template/cf-apps-pipeline.yml.erb, concourse/pipelines/template/k8s-pipeline.yml.erb, concourse/pipelines/template/news-pipeline.yml.erb, concourse/tasks/extract_terraform_outputs.yml, concourse/tasks/generate-all-pipelines.yml, concourse/tasks/git_append_a_dir_from_generated/task.yml, concourse/tasks/git_update_a_dir_from_generated.yml, concourse/tasks/git_update_a_file_from_generated.yml, concourse/tasks/git_update_all_files_from_generated.yml, docs/reference_dataset/template_repository/hello-world-root-depls/pipeline-sample/concourse-pipeline-config/pipeline-sample-tpl.yml, spec/scripts/generate-depls/fixtures/references/apps-depls-cf-apps-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-k8s-ref.yml, spec/scripts/generate-depls/fixtures/references/simple-depls-news-ref.yml
=> polish pipelines

ci/Readme.md, ci/bootstrap_coa_env/bosh-deployment-manifest-prereqs.yml, ci/bootstrap_coa_env/bosh-prereqs.example.yml, ci/bootstrap_coa_env/concourse-prereqs.example.yml, ci/bootstrap_coa_env/git-server-manifest-prereqs.yml, ci/bootstrap_coa_env/pipeline-vars-concourse-pipeline-prereqs.yml, ci/bootstrap_coa_env/pipeline-vars-iaas-prereqs.yml, ci/bootstrap_coa_env/pipeline-vars-ldap-prereqs.yml, ci/bootstrap_coa_env/pipeline-vars-s3-prereqs.yml, ci/bootstrap_coa_env/virtualbox/git-server-manifest-prereqs.yml, docs/reference_dataset/template_repository/another-world-root-depls/another-bosh-deployment-sample/template/another-bosh-deployment-sample-tpl.yml, docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/bosh-deployment-sample-tpl.yml, docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/template/openstack/ntp-job-configuration-operators.yml, docs/reference_dataset/template_repository/hello-world-root-depls/root-deployment.yml
we need minimal vms for test instances.
=> chore(ci): downsize flavor used in test

concourse/pipelines/bootstrap-all-init-pipelines.yml, concourse/pipelines/shared/concourse-pipeline.yml.erb, concourse/pipelines/shared/control-plane-pipeline.yml.erb, concourse/pipelines/shared/kubernetes-pipeline.yml.erb, spec/lib/template_processor/template_processor_for_shared_control_plane_pipeline_spec.rb, spec/scripts/generate-depls/fixtures/references/simple-shared-control-plane.yml, spec/scripts/generate-depls/fixtures/references/simple-shared-kubernetes.yml, spec/scripts/generate-depls/fixtures/references/simple-shared-update.yml
we also fix wrong pipeline name
=> concourse(pipelines): polishing unpause mechanism

concourse/pipelines/template/k8s-pipeline.yml.erb, scripts/generate-and-load-pipeline.sh, spec/scripts/generate-depls/fixtures/references/simple-depls-k8s-ref.yml
We need to target jobs in k8s pipeline. We also fix a typo in a script.
=> pipeline(k8s): fix re-trigger all jobs

Dockerfile, docs/reference_dataset/template_repository/hello-world-root-depls/root-deployment.yml
- bump concourse to 9.7.1
- update Docker image
=> Update COA CI env

concourse/pipelines/template/bosh-precompile-pipeline.yml.erb, spec/scripts/generate-depls/fixtures/references/simple-depls-bosh-precompile-ref.yml
We ensure 'error' and 'blobstore' keywords are matched on the same line...
=> pipeline(precompile): refine blobstore related error detection

Gemfile, Gemfile.lock, concourse/pipelines/shared/kubernetes-pipeline.yml.erb, concourse/tasks/execute_k8s_shells/run.sh, lib/coa/env_bootstrapper/git.rb, spec/lib/coa/env_bootstrapper/git_spec.rb
- pipeline(kubernetes): fix local secret scan
- test(env_bootstrapper): ensure git commit messages are safe 
- test(tasks/execute_k8s_shells): fix dubious ownership error
=> Fix local secret scan on shared k8s
